
export const MOCK_PROPERTIES = [
  {
    id: 1,
    type: 'villa',
    coverImage: 'https://picsum.photos/seed/villa1/800/600',
    address: {
      en: 'Modern Villa in the Hills',
      ar: 'فيلا حديثة في التلال',
    },
    price: 1200000,
    size: 450,
    bedrooms: 5,
    livingRooms: 2,
    balconies: 3,
    kitchens: 1,
    bathrooms: 4,
    furnished: true,
    constructionYear: 2022,
    waterSource: 'Well',
    electricitySource: ['Solar'],
    mapsLink: 'https://goo.gl/maps/1',
    parking: 3,
    totalFloors: 2,
    elevator: false,
    description: 'A stunning modern villa with panoramic views of the city. Features a private pool, garden, and state-of-the-art security system.'
  },
  {
    id: 2,
    type: 'apartment',
    coverImage: 'https://picsum.photos/seed/apt1/800/600',
    address: {
      en: 'Chic Downtown Apartment',
      ar: 'شقة أنيقة في وسط المدينة',
    },
    price: 450000,
    size: 180,
    bedrooms: 3,
    livingRooms: 1,
    balconies: 2,
    kitchens: 1,
    bathrooms: 2,
    furnished: true,
    constructionYear: 2020,
    waterSource: 'Municipal',
    electricitySource: ['Building Generator'],
    mapsLink: 'https://goo.gl/maps/2',
    parking: 1,
    totalFloors: 10,
    floorNumber: 7,
    elevator: true,
  },
  {
    id: 3,
    type: 'commercial',
    coverImage: 'https://picsum.photos/seed/comm1/800/600',
    address: {
      en: 'Prime Commercial Space',
      ar: 'مساحة تجارية مميزة',
    },
    price: 850000,
    size: 300,
    bedrooms: 0,
    livingRooms: 0,
    balconies: 0,
    kitchens: 1,
    bathrooms: 2,
    furnished: false,
    constructionYear: 2018,
    waterSource: 'Municipal',
    electricitySource: ['Building Generator', 'Other'],
    mapsLink: 'https://goo.gl/maps/3',
    parking: 5,
    totalFloors: 5,
    floorNumber: 2,
    elevator: true,
    description: 'Excellent commercial space in a high-traffic area, suitable for retail or office use. Includes a kitchenette and two bathrooms.'
  },
  {
    id: 4,
    type: 'land',
    coverImage: 'https://picsum.photos/seed/land1/800/600',
    address: {
      en: 'Spacious Land with Sea View',
      ar: 'أرض واسعة بإطلالة على البحر',
    },
    price: 600000,
    size: 5000,
    bedrooms: 0,
    livingRooms: 0,
    balconies: 0,
    kitchens: 0,
    bathrooms: 0,
    furnished: false,
    constructionYear: 0,
    waterSource: 'N/A',
    electricitySource: [],
    mapsLink: 'https://goo.gl/maps/4',
    parking: 0,
  },
  {
    id: 5,
    type: 'apartment',
    coverImage: 'https://picsum.photos/seed/apt2/800/600',
    address: {
      en: 'Cozy Suburban Apartment',
      ar: 'شقة مريحة في الضواحي',
    },
    price: 320000,
    size: 120,
    bedrooms: 2,
    livingRooms: 1,
    balconies: 1,
    kitchens: 1,
    bathrooms: 1,
    furnished: false,
    constructionYear: 2019,
    waterSource: 'Municipal',
    electricitySource: ['Solar'],
    mapsLink: 'https://goo.gl/maps/5',
    parking: 1,
    totalFloors: 4,
    floorNumber: 2,
    elevator: false,
  },
  {
    id: 6,
    type: 'villa',
    coverImage: 'https://picsum.photos/seed/villa2/800/600',
    address: {
        en: 'Luxury Beachfront Villa',
        ar: 'فيلا فاخرة على شاطئ البحر'
    },
    price: 2500000,
    size: 600,
    bedrooms: 6,
    livingRooms: 2,
    balconies: 4,
    kitchens: 2,
    bathrooms: 5,
    furnished: true,
    constructionYear: 2023,
    waterSource: 'Municipal',
    electricitySource: ['Building Generator'],
    mapsLink: 'https://goo.gl/maps/6',
    parking: 4,
    totalFloors: 3,
    elevator: true,
    description: 'An exquisite villa located directly on the beach, offering unparalleled luxury and direct access to the sea. Perfect for families or as a high-end vacation rental.'
  }
];
